#!/usr/bin/env python
import subprocess
from os import listdir
from os.path import isfile, join
mypath = 'test'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath,f))]
for f in onlyfiles:
    if '.' in f:
        continue
    print("\nRunning test set: " + f)
    subprocess.call(join(mypath,f))
