#!/bin/bash
mkdir lib

wget https://raw.githubusercontent.com/philsquared/Catch/develop/single_include/catch.hpp 
mv catch.hpp lib/_catch.hpp

wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download 
tar -xvf download 
mkdir -p lib/boost_subset
bcp --boost="boost_1_58_0" python "lib/boost_subset"
rm -r boost_1_58_0
rm download

wget http://bitbucket.org/eigen/eigen/get/3.2.4.tar.gz
tar -xvf 3.2.4.tar.gz
rm -r 3.2.4.tar.gz
mv eigen* lib/eigen
